version: "3.9"
services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./app:/app/app      # アプリケーションソースのみ
      - ./components:/app/components
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.ts:/app/next.config.ts
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules   # node_modules はコンテナ側に分離
      - /app/.next          # .next はコンテナ側に分離
    command: sh -c "npm install --legacy-peer-deps && echo '=== TAILWIND CHECK ===' && npm list tailwindcss && echo '=== POSTCSS CHECK ===' && npm list postcss && echo '=== STARTING DEV ===' && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
